spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rapido_userdb
    username: root
    password: Meghana@123
  jpa:
#    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      default: ${EUREKA_URI:http://localhost:8761/eureka}
